### ISSUE TITLE
Suggestion: Include instructions for compiling with ttypescript in Readme

### ISSUE THREAD

**Issue by hugoaboud** [adonisjs/ioc-transformer#8]
I'm building a lib which depends on Adonis, so I needed to use `ioc-transformer` to fix the imports.

The readme currently shows an example on how to use it with `ts-node`, however I needed to generate the `.js` and `.d.ts` files for serving the library, so I went with [ttypescript](https://github.com/cevek/ttypescript).

Since it took me some time to figure out how to make it work, I've decided to share it here. If it's not "readme material", the issue itself might be helpful for someone in the future.

1. Add `ttypescript` to the project
```bash
yarn add --dev ttypescript
``` 

2. Create a `transformers/ioc.ts` file:
```typescript
import { iocTransformer } from '@adonisjs/ioc-transformer';
import * as ts from 'typescript';
import adonisrc from "../.adonisrc.json"

export default function IocTransformer() {
    return {
        after: iocTransformer(ts, adonisrc)
    }
}
```

3. Add the transformer to the `tsconfig.json`:
```json
"compilerOptions": {
  "plugins": [
    {
      "transform": "./transformers/ioc.ts"
    },
  ],
}
```

4. Use `ttypescript` to compile the files:
```bash
ttsc
```

**Comment by thetutlage** [comment]
Thanks for sharing. I believe, we can add it to README as well. So feel free to open a PR for it

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
